# Generated by Django 3.2.9 on 2021-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.DateTimeField()),
                ('timezone_offset', models.DateTimeField()),
                ('current', models.TextField()),
                ('minutely', models.TextField()),
                ('hourly', models.TextField()),
                ('daily', models.TextField()),
                ('city', models.CharField(choices=[('AUSTIN', 'Austin'), ('PUNE', 'Pune'), ('SANTABARBARA', 'Santabarbara')], max_length=20)),
            ],
        ),
    ]
